Made some changes to error handling and fixed a compilation error.
`cuda::describe` when on an error in getting the error string with `cuGetErrorString`, now
attempts to run `cudaGetErrorString` (from the runtime API) since `cuda::status_t` represents `CUResult` and `cudaError_t`.

The `enqueue_raw_kernel_launch_in_current_context` now also checks for an error with `cudaGetLastError` along with `cuda::outstanding_error::ensure_none`, since kernel launch errors like `cudaErrorInvalidConfiguration` went uncaught.

Changed

 ```diff
-template <typename MarshalTarget, typename Delimiter>
-MarshalTarget& operator<<(MarshalTarget& mt, detail_::opt_start_t<Delimiter>& opt_start)
+template <typename Delimiter>
+std::ostream& operator<<(std::ostream& mt, detail_::opt_start_t<Delimiter>& opt_start)
 ```

since there were ~63 compiler errors in the vein of:

```
C:\local\cuda-api-wrappers\src\cuda\rtc/compilation_options.hpp(585): error : more than one operator "<<" matches these operands:
            function template "MarshalTarget &cuda::rtc::operator<<(MarshalTarget &, cuda::rtc::detail_::opt_start_t<Delimiter> &)"
(489): here
            function template "cuda::rtc::marshalled_options_t &cuda::rtc::marshalled_options_t::operator<<(T &&)"
C:\local\cuda-api-wrappers\src\cuda\rtc\detail/marshalled_options.hpp(53): here
            operand types are: cuda::rtc::marshalled_options_t << cuda::rtc::detail_::opt_start_t<void (*)()>
          detected during:
            instantiation of "void cuda::rtc::process(const cuda::rtc::compilation_options_t<cuda::ptx> &, MarshalTarget &, Delimiter, __nv_bool) [with MarshalTarget=cuda::rtc::marshalled_options_t, Delimiter=void (*)()]"
(689): here
            instantiation of "cuda::rtc::marshalled_options_t cuda::rtc::marshal(const cuda::rtc::compilation_options_t<Kind> &) [with Kind=cuda::ptx]"
C:\local\cuda-api-wrappers\src\cuda\rtc/program.hpp(567): here
```

Updated the macros (`throw_if_error_lazy`, `throw_if_rtc_error_lazy` and `CAW_SET_SCOPE_CONTEXT`) to refer to functions by their absolute paths.